# NOTE: Spring CLoud Vault configuration (https://docs.spring.io/spring-cloud-vault/reference/)
# NOTE: Enterprise HashiCorp Vault
spring:
  application:
    name: vault-app
  config:
    # NOTE: https://docs.spring.io/spring-cloud-vault/reference/config-data.html
    import: vault://secret/runtime/example/path_to_secret?prefix=SOME_CREDENTIALS_SECRET.  # FIXME: change-it
  cloud:
    vault:
      kv:
        enabled: true
      fail-fast: true
      session:
        lifecycle:
          enabled: true
      config:
        lifecycle:
          enabled: true

# NOTE: Custom configuration for vault
vault:
  uami:
    uri: https://vault.example.dev.net # FIXME: change-it
    namespace: XYZ123 # FIXME: change-it
    role: uami_dev_xyz_001 # FIXME: change-it
    resource: api://vault.dev.net # FIXME: change-it
    client-id:   # FIXME: change-it

# NOTE: Secret to be sourced from vault
secret:
  from:
    vault: $(SOME_CREDENTIALS_SECRET.secret) # FIXME: change-it

management:
  health:
    vault:
      enabled: false